#!/bin/sh

set -eu

psql \
  -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set=postgrest_password="$POSTGREST_DB_PASSWORD" <<'EOSQL'

-- =========================================================
-- ROLES
-- =========================================================

-- Role usada para executar as operações da API.
-- Não possui senha e não pode fazer login diretamente.
CREATE ROLE task_api
  NOLOGIN;

-- Role utilizada pelo processo do PostgREST para conectar.
-- Possui login, mas não recebe permissões diretamente.
CREATE ROLE postgrest_authenticator
  LOGIN
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOSUPERUSER
  PASSWORD :'postgrest_password';

-- Permite que o authenticator execute SET ROLE task_api.
GRANT task_api TO postgrest_authenticator;


-- =========================================================
-- SCHEMA EXPOSTO PELO POSTGREST
-- =========================================================

CREATE SCHEMA api;


-- =========================================================
-- TABELA USERS
-- =========================================================

CREATE TABLE api.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  username text NOT NULL,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- =========================================================
-- TABELA BOARDS
-- =========================================================

CREATE TABLE api.boards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL
    REFERENCES api.users(id)
    ON DELETE CASCADE,
  title text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX boards_user_id_idx
ON api.boards (user_id);


-- =========================================================
-- TABELA TASKS
-- =========================================================

CREATE TABLE api.tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id integer NOT NULL
    REFERENCES api.boards(id)
    ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  completed boolean NOT NULL DEFAULT false
);

CREATE INDEX tasks_board_id_idx
ON api.tasks (board_id);


-- =========================================================
-- PERMISSÕES DA API
-- =========================================================

-- Permite enxergar os objetos existentes no schema.
GRANT USAGE ON SCHEMA api TO task_api;


-- Permissões necessárias para o CRUD do task manager.
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE api.tasks
TO task_api;

-- Permite gerar automaticamente o id da nova task.
GRANT USAGE
ON SEQUENCE api.tasks_id_seq
TO task_api;


-- Permite cadastrar e consultar usuários.
GRANT SELECT, INSERT
ON TABLE api.users
TO task_api;

-- Permite gerar automaticamente o id do usuário.
GRANT USAGE
ON SEQUENCE api.users_id_seq
TO task_api;


-- Permite cadastrar e consultar boards.
GRANT SELECT, INSERT
ON TABLE api.boards
TO task_api;

-- Permite gerar automaticamente o id do board.
GRANT USAGE
ON SEQUENCE api.boards_id_seq
TO task_api;

EOSQL